cart:
	bash components/cart.sh
catalogue:
	bash components/catalogue.sh
dispatch:
	bash components/dispatch.sh
frontend:
	bash components/frontend.sh
mongodb:
	bash components/mongodb.sh
mysql:
	bash components/mysql.sh
payment:
	bash components/payment.sh
rebbimq:
	bash components/rebbitmq.sh
redis:
	bash components/redis.sh
shipping:
	bash components/shipping.sh
user:
	bash components/user.sh
